# Generated by Django 5.0.2 on 2024-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
