# Generated by Django 5.0.2 on 2024-08-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_run_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='runner',
            new_name='athlete',
        ),
    ]
