# Generated by Django 5.0.2 on 2024-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(default='init', max_length=50),
        ),
    ]
