# Generated by Django 5.0.2 on 2024-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
