# Generated by Django 5.0.2 on 2024-10-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0008_run_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
