# Generated by Django 5.0.2 on 2024-10-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0009_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
