# Generated by Django 5.0.2 on 2024-10-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0010_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
