# Generated by Django 5.0.2 on 2024-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0012_position_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
