# Generated by Django 5.0.2 on 2024-10-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0013_alter_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
