# Generated by Django 5.0.2 on 2024-10-28 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0018_alter_athletecoachrelation_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athletecoachrelation',
            unique_together={('athlete', 'coach')},
        ),
    ]
