# Generated by Django 5.0.2 on 2024-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0022_alter_challengerecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengerecord',
            name='name',
            field=models.CharField(choices=[('RUN_10', 'Сделай 10 Забегов!'), ('RUN_50', 'Пробеги 50 километров!'), ('RUN_2_10', 'Пробеги 2 километра меньше чем за 10 минут!')], default='', max_length=255),
        ),
    ]
