# Generated by Django 5.0.2 on 2024-11-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0023_alter_challengerecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletecoachrelation',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
