# Generated by Django 5.0.2 on 2024-11-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0025_athleteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='comment',
            new_name='goals',
        ),
    ]
