# Generated by Django 5.1.3 on 2024-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0032_athleteinfo_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='test_field',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
