# Generated by Django 5.1.3 on 2024-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0033_alter_athleteinfo_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('picture', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
