# Generated by Django 5.1.3 on 2024-12-10 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0035_collectableitem_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectableitem',
            name='users',
            field=models.ManyToManyField(related_name='collectable_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
