# Generated by Django 5.1.3 on 2024-12-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0036_collectableitem_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteinfo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='athleteinfo',
            name='test_field',
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
