# Generated by Django 5.0.2 on 2025-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0038_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengerecord',
            name='name',
            field=models.CharField(choices=[('RUN_10', 'Сделай 10 Забегов!'), ('RUN_50', 'Пробеги 50 километров!'), ('RUN_2_10', '2 километра за 10 минут!')], default='', max_length=255),
        ),
    ]
