# Generated by Django 5.0.2 on 2025-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0039_alter_challengerecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteinfo',
            name='weight',
        ),
        migrations.AddField(
            model_name='athleteinfo',
            name='test_field',
            field=models.CharField(default='', max_length=255),
        ),
    ]
