# Generated by Django 5.0.2 on 2025-03-28 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0040_remove_athleteinfo_weight_athleteinfo_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
