# Generated by Django 5.1.7 on 2025-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0042_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(),
        ),
    ]
