# Generated by Django 5.1.7 on 2025-05-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0043_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
