# Generated by Django 5.1.7 on 2025-06-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0045_alter_run_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
